
RUSH_E_AUTOPLAY_LABEL = "Autoplay locked, your fingers lost custody"
RUSH_E_LOCK_MESSAGE = "Rush E detected: autoplay is locked on. Your fingers lost custody."
RUSH_E_RUNTIME_LOCK_LINE = "Autoplay locked, Saul said your fingers need a plea deal"

LAUNCHER_ROASTS = [
    "Walt cooked. You burnt the metronome.",
    "Heisenberg level ego, Jesse level timing.",
    "Saul Goodman would not put this combo on retainer.",
    "Better Call Autoplay.",
    "Gus Fring inspected your rhythm and closed the restaurant.",
    "Mike saw your timing and asked for hazard pay.",
    "Lalo heard that rhythm and started smiling.",
    "Hector rang once for every missed note.",
    "Los Pollos could not fry this performance enough.",
    "Chuck would call this electricity abuse.",
    "Howard's reputation recovered faster than your combo.",
    "Your tempo is blue, but not the premium product.",
    "The cartel has standards. Your left hand does not.",
    "Jesse asked for science, your rhythm gave him a crime scene.",
    "Skyler looked at your accuracy and started laundering silence.",
    "Nacho changed sides to avoid your metronome.",
    "Your practice log looks like a DEA evidence board.",
    "That chord progression needs witness protection.",
    "Homelander level confidence, Deep-level execution.",
    "Omni-Man would ask why you are still trying manually.",
    "Night City called; your reflex implant is on backorder.",
    "Dutch has a plan. Your timing does not.",
    "Arthur Morgan had better dead-eye after tuberculosis.",
    "Harvey Specter would settle this before the first chorus.",
    "Pearson Hardman cannot bill enough hours to defend that combo.",
    "Vought legal reviewed your performance and enabled autoplay.",
    "You are not him. The autoplayer is him.",
    "The metronome filed a hostile workplace complaint.",
    "Learning mode is generous. The song is not.",
    "The piano has rejected your audition tape.",
    "This is not practice. This is a deposition with keys.",
    "Tommy Shelby planned six moves ahead. You missed C.",
    "House would diagnose this as terminal rhythm.",
    "John Wick retired for less disrespect than that miss.",
    "Your fingers are committing securities fraud against the beat.",
    "This run has all the structure of a cartel startup.",
    "Dexter would wrap that combo in plastic.",
    "True Detective found symbols in your missed notes.",
]

LEARNING_HUD_ROASTS = [
    "Gus closed the restaurant after that timing.",
    "Mike found your rhythm unreliable.",
    "Lalo is smiling. That is not good.",
    "Hector rang once per missed note.",
    "Kim Wexler objected to your fingering.",
    "Chuck called this electricity abuse.",
    "Heisenberg ego. Jesse timing.",
    "Saul would plea-bargain that accuracy.",
    "The DEA is tracking your tempo.",
    "Tuco called that rhythm volatile.",
    "Nacho would rather switch hands.",
    "Gale wrote cleaner lab notes than that run.",
    "Skinny Pete has more flow than this.",
    "Badger would not even pirate that performance.",
    "Fring-level planning, street-corner execution.",
    "Homelander confidence. Deep-level accuracy.",
    "Omni-Man saw that combo and left orbit.",
    "Night City called: your chrome is just lag.",
    "Dutch has a plan. Your hands do not.",
    "Harvey Specter would not take this case.",
    "Vought rejected this for liability.",
    "You are not him. Autoplay is him.",
    "Main character energy, tutorial execution.",
    "The notes unionized against your fingers.",
    "Tony sent your rhythm to therapy.",
    "House diagnosed terminal rhythm.",
    "Logan Roy fired your tempo.",
    "John Wick would avenge that missed note.",
    "Dexter labeled that combo evidence.",
]

AUTOPLAY_ROASTS = [
    "Autoplay ON - Better Call Saul called this mercy",
    "Autoplay ON - Gus closed your manual shift",
    "Autoplay ON - Mike benched your fingers",
    "Autoplay ON - Hector rang for every miss",
    "Autoplay ON - Kim objected to the fingering",
    "Autoplay ON - Heisenberg cooked, you microwaved",
    "Autoplay ON - Los Pollos rejected the rhythm",
    "Autoplay ON - Lalo is smiling at your timing",
    "Autoplay ON - Tuco called your tempo unstable",
    "Autoplay ON - Nacho requested a safer crew",
    "Autoplay ON - Saul filed a motion against manual",
    "Autoplay ON - Jesse said the science failed",
    "Autoplay ON - Gus scheduled a performance review",
    "Autoplay ON - Mike cleaned up your combo",
    "Autoplay ON - Vought legal said supervision",
    "Autoplay ON - Omni-Man said think, then took over",
    "Autoplay ON - Night City downgraded your reflexes",
    "Autoplay ON - Dutch's plan beat your timing",
    "Autoplay ON - Harvey settled your accuracy",
    "Autoplay ON - your hands failed the audition",
    "Autoplay ON - main character privileges revoked",
    "Autoplay ON - piano requested a better operator",
    "Autoplay ON - House diagnosed terminal rhythm",
    "Autoplay ON - John Wick saw the miss and reloaded",
    "Autoplay ON - Dexter bagged the evidence",
]
